### PR TITLE
feat: support env parameter ENDPOINT_URL to helps locate the sp…

### PR DESCRIPTION
**Pull request by koljahuang**
…ecified aws service entrypoint

- #579

*Description of changes:*
When integrating with localstack, it reports that the security token included in the request is invalid. The reason is that the profile was not successfully passed when creating the session somewhere. The easiest way to modify it is to specify the endpoint through environment variables when creating boto3 client.

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

### CODE REVIEW

**Comment by dgraeber** [comment]
@koljahuang thanks for this PR.  For SeedFarmer core functionality, we will not be supporting references to env parameters (as opposed to to configs derived from manifests).  All core functionality for SF will be configured via the manifests or via `seedfarmer.yaml`.

SeedFarmer does indeed support the use of profiles (if you pass it in, we will use it).  

Based on the information you provided, I think there is a deeper issue.  Typically when you get this error, it is due to the session used to invoke the auto-generated does not align -- primarily because boto3 session is not thread safe.   I think this PR / FR will obfuscate a deeper issue.  

Please issue a FR and describe in detail the issue you are having.

**Comment by dgraeber** [comment]
@koljahuang Would using the standard HTTP proxy support in seedfarmer accommodate your request:

https://seed-farmer.readthedocs.io/en/latest/cli_commands.html#http-proxy-support

That is definitely leveraging env pararameters (we wanted to mimic how boto3 has implemented).

**Comment by koljahuang** [comment]
> Also....after researching, I believe you are referring to LocalStack (https://github.com/localstack/localstack) and your use case is to develop locally? If so, please confirm?

Yes. I  want to integrate seed-farmer with localstack. It works when i use env variable:
```sh
(.venv) ➜  mynewproject git:(master) seedfarmer apply manifests/deployment.yaml --env-file .env --profile localstack --dry-run
[2024-05-11 15:14:50,228 | INFO | utils.py     :181 | MainThread ] Loading environment variables from .env
[2024-05-11 15:14:50,229 | INFO | __main__.py  :147 | MainThread ] Apply request with manifest manifests/deployment.yaml
 ***   This is a dry-run...NO ACTIONS WILL BE TAKEN  ***
[2024-05-11 15:14:50,231 | INFO | session_manager.py:178 | MainThread ] Creating toolchain session
[2024-05-11 15:14:50,420 | INFO | _deployment_commands.py:267 | MainThread ] Priming Accounts
[2024-05-11 15:14:50,422 | INFO | _deployment_commands.py:277 | Prime-Accounts-0-000000000000-us-east-1 ] Priming Acccount 000000000000 in us-east-1
[2024-05-11 15:14:50,422 | INFO | session_manager.py:125 | Prime-Accounts-0-000000000000-us-east-1 ] Creating Session for 000000000000-us-east-1
[2024-05-11 15:14:50,608 | INFO | _seedkit_commands.py: 90 | Prime-Accounts-0-000000000000-us-east-1 ] Deploying Seedkit mynewproject with Stack Name aws-codeseeder-mynewproject
[2024-05-11 15:14:55,771 | INFO | _seedkit_commands.py:111 | Prime-Accounts-0-000000000000-us-east-1 ] Seedkit Deployed
[2024-05-11 15:14:55,810 | INFO | _stack_commands.py:107 | Prime-Accounts-0-000000000000-us-east-1 ] Resolved the ProjectPolicyPath /Users/huangchao/tmp/localStack_seedFarmer_pytest_stepfunctionsCDK/.venv/lib/python3.11/site-packages/seed_farmer-3.6.0.dev0-py3.11.egg/seedfarmer/resources/projectpolicy.yaml
[2024-05-11 15:14:55,811 | INFO | _stack_commands.py:112 | Prime-Accounts-0-000000000000-us-east-1 ] Deploying mynewproject-managed-policy from the path /Users/huangchao/tmp/localStack_seedFarmer_pytest_stepfunctionsCDK/.venv/lib/python3.11/site-packages/seed_farmer-3.6.0.dev0-py3.11.egg/seedfarmer/resources/projectpolicy.yaml
Nothing to destroy
Modules added to manifest: example
┏━━━━━━━━━┳━━━━━━━━━━━┳━━━━━━━━━━━━┳━━━━━━━━━┳━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━━┓
┃ Account ┃ Region    ┃ Deployment ┃ Group   ┃ Module ┃ Path                     ┃
┡━━━━━━━━━╇━━━━━━━━━━━╇━━━━━━━━━━━━╇━━━━━━━━━╇━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━┩
│ primary │ us-east-1 │ example    │ mygroup │ mytest │ modules/mygroup/mymodule │
└─────────┴───────────┴────────────┴─────────┴────────┴──────────────────────────┘
[2024-05-11 15:15:01,053 | INFO | _deployment_commands.py:481 | MainThread ]  Verifying all modules in mygroup for deploy
Modules scheduled to be deployed (created or updated):
example
┏━━━━━━━━━┳━━━━━━━━━━━┳━━━━━━━━━━━━┳━━━━━━━━━┳━━━━━━━━┓
┃ Account ┃ Region    ┃ Deployment ┃ Group   ┃ Module ┃
┡━━━━━━━━━╇━━━━━━━━━━━╇━━━━━━━━━━━━╇━━━━━━━━━╇━━━━━━━━┩
│ primary │ us-east-1 │ example    │ mygroup │ mytest │
└─────────┴───────────┴────────────┴─────────┴────────┘
To see all deployed modules, run seedfarmer list modules -d example
```
I will check and try to use the standard HTTP proxy support as workaound.

**Comment by koljahuang** [comment]
> @koljahuang thanks for this PR. For SeedFarmer core functionality, we will not be supporting references to env parameters (as opposed to to configs derived from manifests). All core functionality for SF will be configured via the manifests or via `seedfarmer.yaml`.
> 
> Please issue a FR and describe in detail the issue you are having. Based on the information you provided, I think there is a deeper issue. Typically when you get this error, it is due to the session used to invoke the auto-generated endpoint url does not align -- primarily because boto3 session is not thread safe. But, we also understand that there may be restrictive networking issues with some customers.
> 
> Once you issue the FR with detailed issues, we can assess.
> 
> Some log output would also be helpful.

I have created feature request. Pls check #579

**Pull request closed without merging**
